export const NEW_IDEA = 'NEW_IDEA';
export const GET_ONE_IDEA = 'GET_ONE_IDEA';
export const UP_VOTE = 'UP_VOTE';
export const UN_VOTE = 'UN_VOTE';
export const DELETE_IDEA = 'DELETE_IDEA';
export const UPDATE_IDEA = 'UPDATE_IDEA';
export const BRANCH_IDEA_TO_BOARD = 'BRANCH_IDEA_TO_BOARD';
export const NEW_BOARD = 'NEW_BOARD';
export const GET_BOARDS = 'GET_BOARDS';
export const GET_ONE_BOARD_REQUEST = 'GET_ONE_BOARD_REQUEST';
export const GET_ONE_BOARD_SUCCESS = 'GET_ONE_BOARD_SUCCESS';
export const GET_ONE_BOARD_ERROR = 'GET_ONE_BOARD_ERROR';
export const DELETE_BOARD = 'DELETE_BOARD';
export const REFRESH_BOARD_VIEW = 'REFRESH_BOARD_VIEW';
export const CLEAR_BOARD_VIEW = 'CLEAR_BOARD_VIEW';
export const REFRESH_ALL_BOARDS = 'REFRESH_ALL_BOARDS';
export const SHUFFLE_IDEAS = 'SHUFFLE_IDEAS';
export const SORT_IDEAS_BY_VOTES = 'SORT_IDEAS_BY_VOTES';
export const SORT_IDEAS_BY_CONTENT = 'SORT_IDEAS_BY_CONTENT';
export const SORT_IDEAS_BY_TIME = 'SORT_IDEAS_BY_TIME';
export const ADD_COMMENT = 'ADD_COMMENT';
export const SYNC_COMMENT = 'SYNC_COMMENT';
export const DELETE_COMMENT = 'DELETE_COMMENT';
export const GET_MESSAGES = 'GET_MESSAGES';
export const ADD_MESSAGE = 'ADD_MESSAGE';
export const GET_ACTIVEUSER = 'GET_ACTIVEUSER';
export const ADD_ACTIVEUSER = 'ADD_ACTIVEUSER';
export const DELETE_ACTIVEUSER = 'DELETE_ACTIVEUSER';

// Timed Boards
export const NEW_TIMED_IDEA = 'NEW_TIMED_IDEA';
export const UPDATE_TIMED_IDEA = 'UPDATE_TIMED_IDEA';
export const DELETE_TIMED_IDEA = 'DELETE_TIMED_IDEA';
export const NEW_TIMED_BOARD = 'NEW_TIMED_BOARD';
export const PUSH_TIMED_BOARD = 'PUSH_TIMED_BOARD';
export const DELETE_TIMED_BOARD = 'DELETE_TIMED_BOARD';
export const GET_TIMED_BOARD_REQUEST = 'GET_TIMED_BOARD_REQUEST';
export const GET_TIMED_BOARD_SUCCESS = 'GET_TIMED_BOARD_SUCCESS';
export const GET_TIMED_BOARD_ERROR = 'GET_TIMED_BOARD_ERROR';
export const CLEAR_TIMED_BOARD_VIEW = 'CLEAR_TIMED_BOARD_VIEW';
export const SHUFFLE_TIMED_IDEAS = 'SHUFFLE_TIMED_IDEAS';
export const SORT_TIMED_IDEAS_BY_CONTENT = 'SORT_TIMED_IDEAS_BY_CONTENT';
export const SORT_TIMED_IDEAS_BY_TIME = 'SORT_TIMED_IDEAS_BY_TIME';

// User actions
export const SAVE_OR_FETCH_USER = 'SAVE_OR_FETCH_USER';
export const GET_USER_REQUEST = 'GET_USER_REQUEST';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_ERROR = 'GET_USER_ERROR';
export const JOIN_BOARD = 'JOIN_BOARD';
export const LEAVE_BOARD = 'LEAVE_BOARD';
export const SEND_EMAIL = 'SEND_EMAIL';

// Auth Actions
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOCK_SUCCESS = 'LOCK_SUCCESS';
export const LOCK_ERROR = 'LOCK_ERROR';
